### ISSUE TITLE
Cannot find module 'uws'

### ISSUE THREAD

**Issue by Yang-Siqi** [Billy4195/EEG-gui#12]
'''
throw new Error('Compilation of µWebSockets has failed and there is no pre-compiled binary ' +
            ^

Error: Compilation of µWebSockets has failed and there is no pre-compiled binary available for your system. Please install a supported C++11 compiler and reinstall the module 'uws'.
'''
I always get the above error message. And sometimes it tells me that **"Cannot find module 'uws'"*.
I couldn't find anymore information about this issue online, can you please direct me on how to figure out what is causing this issue?

Thanks

**Comment by Billy4195** [comment]
How did you get this error? By executing which file?

**Comment by Yang-Siqi** [comment]
npm install
node server.js
then I got those errors
I do not know whether they are the right steps.

**Comment by Billy4195** [comment]
maybe that is the problem related to versions of the used packages.
Could you try to install packages closest to the version listed on the `package.json`?

**Comment by Yang-Siqi** [comment]
I try to use `npm install uNetworking/uWebSockets.js#v17.1.0` and change the `require("uws").Server` into `const wsServer = require("uWebSockets.js").Server`It seems like it works.  however it gives me a new error 
```
E:\mockupServer\server.js:68
        let wss = new wsServer({ port: this.port }, () => {
                  ^

TypeError: wsServer is not a constructor
```
I am not familiar with WebSocket. Could you please help me?
Thanks!

**Comment by Billy4195** [comment]
After checking the newest `uws`, I think this problem is because they change the interface to use this package. 
(I guess you should use `const wsServer = require("uWebSockets.js").App` instead of `Server`)
If you wish to use v17.1.0, please refer to their [docs](https://unetworking.github.io/uWebSockets.js/generated/index.html) or [examples](https://github.com/uNetworking/uWebSockets.js/tree/master/examples), or you can choose to use the sample version as mine v10.148.1 (node v8.12.0)

**Comment by kirintwn** [comment]
I may be able to fix this, will create a PR is it works.
